config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
      }
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  get '/pages/users', to: 'pages#users'
  get '/pages/admin', to: 'pages#admin'

  resources :collections, only: %i[index new create]

  root "pages#index"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :user_id, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  # before_action :logged_in_user, only: [:create, :destroy]
  def new
    @collection = Collection.new(collection_params.merge(user: current_user))
  end

  # def create
  #   @collection = current_user.collections.build(collection_params)
  #   if @collection.save
  #     flash[:success] = "Collection created!"
  #     redirect_to root_path
  #   end
  # end

  # def destroy
  # end

  # private

  # def collection_params
  #   params.require(:collection).permit(:content)
  # end

  def create
    @collection = Collection.new(collection_params.merge(user: current_user))

    if @collection.save
      redirect_to root_path
    end
  end

  def index
    @collections = Collection.all
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :description, :category)
  end
end

app/views/collections/_form.html.erb
<%= form_with model: Collection.new, url: collections_path, local: true do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>

  <%= f.submit "Submit collection" %>
<% end %>

app/views/collections/index.html.erb
<h1>Collections</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Category</th>
      <th scope="col">Author</th>
    </tr>
  </thead>
  <tbody>
    <% Collection.find_each do |collection| %>
      <tr>
        <th scope="row"><%= collection.id %></th>
        <td><%= collection.name %></td>
        <td><%= collection.description %></td>
        <td><%= collection.category %></td>
        <td><%= collection.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>