config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
        sessions: 'admin/sessions',
        registrations: 'admin/registrations'
      }
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  
  get '/pages/users', to: 'pages#users'
  get '/pages/admin', to: 'pages#admin'

  resources :collections, only: %i[index new create]

  root "pages#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCollect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container">
          <%= link_to 'MyCollect', root_path, class: "nav-link" %>
          <ul class="navbar-nav flex-row flex-wrap ms-md-auto">
            <% if user_signed_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.email %>
              </a>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, class: "nav-link" %>
                </li>
                <li>
                  <%= link_to 'Edit', edit_user_registration_path, class: "nav-link" %>
                </li>
              </ul>

            <% elsif !admin_signed_in? %>

              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
              </li>
            </li> 

            <% elsif admin_signed_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                admin
              </a>

              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Sign out', destroy_admin_session_path, method: :delete, data: {turbo_method: :delete}, class: "nav-link" %>
                </li>
                <li>
                  <%= link_to 'Edit', edit_admin_registration_path, class: "nav-link" %>
                </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </div>
      </nav>

      <main class="container">
        <%= yield %>
      </main>


        <footer class="fixed-bottom text-center text-lg-start text-white" style="background-color: #929fba">
          <div class="container p-4 pb-0">
    
              <div class="row"
                <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h6 class="mb-4 font-weight-bold">
                      For contacts
                    </h6>
                  <% if !user_signed_in? %>  
                  <p>
                    <%= link_to 'Admin', pages_admin_path, class: "text-white text-uppercase mb-4 font-weight-bold" %>
                  </p>
                  <% end %>
                </div>
              </div>
          </div>
        </footer>
      
  </body>
</html>